const labels = {
  csvParser: 'CSV',
  description: 'Description',
  dsvParser: 'DSV',
  entry: 'Entry',
  entries: 'Entries',
  fetcher: 'Fetch strategy',
  field: 'Field',
  format: 'Format',
  htmlParser: 'HTML',
  importance: 'Importance',
  jsonParser: 'JSON',
  mediaType: 'Media type',
  or: 'Alternative path',
  parser: 'Parse strategy',
  path: 'Path',
  saveData: 'Provides',
  serverFetcher: 'Safe',
  standardFetcher: 'Standard',
  query: 'Query',
  requires: 'Requires',
  type: 'Type',
  types: 'Types',
  tsvParser: 'TSV',
  urlTemplate: 'URL Template',
  value: 'Value',
  xmlParser: 'XML'
};

export const translate = (entry) => labels[entry] ? labels[entry] : entry;